DROP SCHEMA ${userName} IF EXISTS;
DROP USER ${userName} IF EXISTS;

CREATE USER IF NOT EXISTS ${userName} PASSWORD '${userName}';
CREATE SCHEMA IF NOT EXISTS ${userName};
GRANT ALL ON SCHEMA ${userName} TO ${userName};

CREATE SEQUENCE ${userName}.POKEMON_ID_SEQ;
CREATE TABLE "${userName}".POKEMON (
  ID     INT DEFAULT ${userName}.POKEMON_ID_SEQ.nextval PRIMARY KEY,
  HP     INT NOT NULL,
  ATTACK INT NOT NULL
);

CREATE TABLE ${userName}.POKEMON_LOCATION (
  X          INT NOT NULL,
  Y          INT NOT NULL,
  POKEMON_ID INT NOT NULL,
  PRIMARY KEY (X, Y),
  FOREIGN KEY (POKEMON_ID) REFERENCES ${userName}.POKEMON (ID)
);

INSERT INTO "${userName}".POKEMON (HP, ATTACK) VALUES (50, 10);
INSERT INTO ${userName}.POKEMON_LOCATION (X, Y, POKEMON_ID) VALUES (2, 3, SELECT ID FROM ${userName}.POKEMON);
